// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiMlAcu4OZ9F70zjdy7R9x8wZDbul4YxM',
    appId: '1:25652470160:web:fc4113be5add461cf45315',
    messagingSenderId: '25652470160',
    projectId: 'travel-guide-app-database',
    authDomain: 'travel-guide-app-database.firebaseapp.com',
    storageBucket: 'travel-guide-app-database.firebasestorage.app',
    measurementId: 'G-K386QQPJQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBQzAFaAgCD-z3TOcBvlLjM5rgXCU3AvY',
    appId: '1:25652470160:android:aec4442db4c9f342f45315',
    messagingSenderId: '25652470160',
    projectId: 'travel-guide-app-database',
    storageBucket: 'travel-guide-app-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTwwMfzwxGOXjAyicBtsjQzC-RFPRxLAQ',
    appId: '1:25652470160:ios:cc08ed1d292a60cff45315',
    messagingSenderId: '25652470160',
    projectId: 'travel-guide-app-database',
    storageBucket: 'travel-guide-app-database.firebasestorage.app',
    iosBundleId: 'com.example.travelGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTwwMfzwxGOXjAyicBtsjQzC-RFPRxLAQ',
    appId: '1:25652470160:ios:cc08ed1d292a60cff45315',
    messagingSenderId: '25652470160',
    projectId: 'travel-guide-app-database',
    storageBucket: 'travel-guide-app-database.firebasestorage.app',
    iosBundleId: 'com.example.travelGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiMlAcu4OZ9F70zjdy7R9x8wZDbul4YxM',
    appId: '1:25652470160:web:f54bfb7f53b4369af45315',
    messagingSenderId: '25652470160',
    projectId: 'travel-guide-app-database',
    authDomain: 'travel-guide-app-database.firebaseapp.com',
    storageBucket: 'travel-guide-app-database.firebasestorage.app',
    measurementId: 'G-97422T41BJ',
  );
}
